/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FairTraceRegistry__factory } from "./FairTraceRegistry__factory";
export { FarmerRegistry__factory } from "./FarmerRegistry__factory";
