# Generated by Django 5.2.4 on 2025-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='public_signals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
