# Generated by Django 5.2.4 on 2025-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('pin', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
