/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fairTraceRegistrySol from "./FairTraceRegistry.sol";
export { Counter__factory } from "./Counter__factory";
