/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FairTraceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getRecord" | "records" | "registerFarmer"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FarmerRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "records", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerFarmer",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFarmer",
    data: BytesLike
  ): Result;
}

export namespace FarmerRegisteredEvent {
  export type InputTuple = [
    farmerId: BytesLike,
    dataHash: BytesLike,
    timestamp: BigNumberish,
    registrar: AddressLike
  ];
  export type OutputTuple = [
    farmerId: string,
    dataHash: string,
    timestamp: bigint,
    registrar: string
  ];
  export interface OutputObject {
    farmerId: string;
    dataHash: string;
    timestamp: bigint;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FairTraceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FairTraceRegistry;
  waitForDeployment(): Promise<this>;

  interface: FairTraceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<
    [farmerId: BytesLike],
    [[string, string, bigint, string]],
    "view"
  >;

  records: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string] & {
        farmerId: string;
        dataHash: string;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;

  registerFarmer: TypedContractMethod<
    [farmerId: BytesLike, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [farmerId: BytesLike],
    [[string, string, bigint, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string] & {
        farmerId: string;
        dataHash: string;
        timestamp: bigint;
        registrar: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerFarmer"
  ): TypedContractMethod<
    [farmerId: BytesLike, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FarmerRegistered"
  ): TypedContractEvent<
    FarmerRegisteredEvent.InputTuple,
    FarmerRegisteredEvent.OutputTuple,
    FarmerRegisteredEvent.OutputObject
  >;

  filters: {
    "FarmerRegistered(bytes32,bytes32,uint256,address)": TypedContractEvent<
      FarmerRegisteredEvent.InputTuple,
      FarmerRegisteredEvent.OutputTuple,
      FarmerRegisteredEvent.OutputObject
    >;
    FarmerRegistered: TypedContractEvent<
      FarmerRegisteredEvent.InputTuple,
      FarmerRegisteredEvent.OutputTuple,
      FarmerRegisteredEvent.OutputObject
    >;
  };
}
