/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ProductRegistry {
  export type ProductRecordStruct = {
    pid: string;
    title: string;
    farmerEmail: string;
    timestamp: BigNumberish;
    metadataURI: string;
  };

  export type ProductRecordStructOutput = [
    pid: string,
    title: string,
    farmerEmail: string,
    timestamp: bigint,
    metadataURI: string
  ] & {
    pid: string;
    title: string;
    farmerEmail: string;
    timestamp: bigint;
    metadataURI: string;
  };
}

export interface ProductRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getProduct" | "owner" | "records" | "registerProduct"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProductRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "getProduct", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "records", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [string, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [
    pid: string,
    title: string,
    farmerEmail: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    pid: string,
    title: string,
    farmerEmail: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    pid: string;
    title: string;
    farmerEmail: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProductRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProductRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProductRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProduct: TypedContractMethod<
    [pid: string],
    [ProductRegistry.ProductRecordStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  records: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, string] & {
        pid: string;
        title: string;
        farmerEmail: string;
        timestamp: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;

  registerProduct: TypedContractMethod<
    [pid: string, title: string, farmerEmail: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [pid: string],
    [ProductRegistry.ProductRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, string] & {
        pid: string;
        title: string;
        farmerEmail: string;
        timestamp: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<
    [pid: string, title: string, farmerEmail: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;

  filters: {
    "ProductRegistered(string,string,string,uint256)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
  };
}
