# Generated by Django 5.2.4 on 2025-11-15 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_transporter_created_at_transporter_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
