# Generated by Django 5.2.4 on 2025-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
    
