# Generated by Django 5.2.4 on 2025-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250910_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
