# Generated by Django 5.2.4 on 2025-09-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otptoken_otp_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
