# Generated by Django 5.2.4 on 2025-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otptoken_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='code',
        ),
    ]
