# Generated by Django 5.2.4 on 2025-09-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_otptoken_code_otptoken_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
