# Generated by Django 5.2.5 on 2025-08-28 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('national_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('farm_address', models.TextField()),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('farm_size', models.FloatField(blank=True, null=True)),
                ('main_crops', models.TextField(blank=True)),
                ('sacco_membership', models.CharField(max_length=100)),
                ('sacco_name', models.CharField(blank=True, max_length=200)),
                ('record_hash', models.CharField(blank=True, max_length=66)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('onchain_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
