# Generated by Django 5.2.4 on 2025-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={},
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='tx_hash',
            new_name='contract_address',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='record_hash',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='insaiderdash@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(default='0000', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='onchain_tx',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gps_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='onchain_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
