# Generated by Django 5.2.4 on 2025-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_farmer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='sacco_name',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='sacco_membership',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
