/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FairTraceRegistry } from "./FairTraceRegistry";
export type { FarmerRegistry } from "./FarmerRegistry";
